# Generated by Django 6.1 on 2026-09-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_offerdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at']},
        ),
    ]
